version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - run: npm test

  deploy:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - run: echo "//registry.npmjs.org/:_authToken=$TOKEN" > ~/repo/.npmrc

      - run: npm publish

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          context: npm
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
